// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdqvUW2xhvtDVBXoi776XLaxKazrsA2zE',
    appId: '1:280398067236:web:793e9fa1bceb8b6ae0cab1',
    messagingSenderId: '280398067236',
    projectId: 'foodprinter-1aa35',
    authDomain: 'foodprinter-1aa35.firebaseapp.com',
    storageBucket: 'foodprinter-1aa35.appspot.com',
    measurementId: 'G-JPJEKSDS3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP9ZdFsBZJPWL_Nb4_UT811L2i634-84k',
    appId: '1:280398067236:android:15b072e05328c6cbe0cab1',
    messagingSenderId: '280398067236',
    projectId: 'foodprinter-1aa35',
    storageBucket: 'foodprinter-1aa35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8ImdzLlV2NfCMWbsh-hlQ4-Nm8IooP5w',
    appId: '1:280398067236:ios:5d75899f7c1458f7e0cab1',
    messagingSenderId: '280398067236',
    projectId: 'foodprinter-1aa35',
    storageBucket: 'foodprinter-1aa35.appspot.com',
    iosBundleId: 'com.foodprinter.dp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8ImdzLlV2NfCMWbsh-hlQ4-Nm8IooP5w',
    appId: '1:280398067236:ios:5d75899f7c1458f7e0cab1',
    messagingSenderId: '280398067236',
    projectId: 'foodprinter-1aa35',
    storageBucket: 'foodprinter-1aa35.appspot.com',
    iosBundleId: 'com.foodprinter.dp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdqvUW2xhvtDVBXoi776XLaxKazrsA2zE',
    appId: '1:280398067236:web:2bf0f7fb712eeb54e0cab1',
    messagingSenderId: '280398067236',
    projectId: 'foodprinter-1aa35',
    authDomain: 'foodprinter-1aa35.firebaseapp.com',
    storageBucket: 'foodprinter-1aa35.appspot.com',
    measurementId: 'G-B4YT2T9DLQ',
  );
}
